name: E-Commerce CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test

      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/eCommerce-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Upload jar to Home Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOME_HOST }}
          username: ${{ secrets.HOME_USERNAME }}
          key: ${{ secrets.HOME_SSH_KEY }}
          source: "eCommerce-0.0.1-SNAPSHOT.jar"
          target: "/home/${{ secrets.HOME_USERNAME }}/ecommerce"

      - name: Restart systemd service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOME_HOST }}
          username: ${{ secrets.HOME_USERNAME }}
          key: ${{ secrets.HOME_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOME_USERNAME }}/ecommerce
            mv -f eCommerce-0.0.1-SNAPSHOT.jar ecommerce.jar
            chown ${{ secrets.HOME_USERNAME }}:${{ secrets.HOME_USERNAME }} ecommerce.jar
            chmod +x ecommerce.jar
            sudo systemctl restart ecommerce.service
